# Generated by Django 5.0.6 on 2024-05-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=19)),
                ('cantidad_existente', models.IntegerField()),
                ('cantidad_vendida', models.IntegerField()),
                ('ventas', models.DecimalField(decimal_places=2, max_digits=19)),
                ('fecha_entrada', models.DateField(auto_now_add=True)),
                ('fecha_salida', models.DateField(auto_now=True)),
            ],
        ),
    ]
